#!/bin/bash
# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -euo pipefail

# npm install if node_modules was removed (e.g. via npm run clean or scripts/clean.sh)
if [ ! -d "node_modules" ]; then
    npm install
fi

# ---- START new code ----
GENERATED_DIR="packages/cli/src/generated"
GIT_COMMIT_TS_FILE="$GENERATED_DIR/git-commit.ts"
GIT_COMMIT_INFO_VALUE="N/A" # Default value

# Create the generated directory if it doesn't exist
mkdir -p "$GENERATED_DIR"

if command -v git &> /dev/null && git rev-parse --is-inside-work-tree &> /dev/null; then
    GIT_HASH=$(git rev-parse --short HEAD 2>/dev/null || echo "")
    if [ -n "$GIT_HASH" ]; then
        GIT_COMMIT_INFO_VALUE="$GIT_HASH"
        if [ -n "$(git status --porcelain 2>/dev/null)" ]; then
            GIT_COMMIT_INFO_VALUE="$GIT_HASH (local modifications)"
        fi
    else
        GIT_COMMIT_INFO_VALUE="unknown (git error)"
    fi
else
    GIT_COMMIT_INFO_VALUE="N/A (not a git repo or git not found)"
fi

# Write to a TypeScript file in the generated directory using a heredoc
cat <<EOL > "$GIT_COMMIT_TS_FILE"
/**
 * @license
 * Copyright $(date +%Y) Google LLC
 * SPDX-License-Identifier: Apache-2.0
 */

// This file is auto-generated by the build script (scripts/build.sh)
// Do not edit this file manually.
export const GIT_COMMIT_INFO = '$GIT_COMMIT_INFO_VALUE';
EOL
# ---- END new code ----

# build all workspaces/packages
npm run build --workspaces

# also build container image if sandboxing is enabled
# skip (-s) npm install + build since we did that above
if scripts/sandbox_command.sh -q && [[ "${BUILD_SANDBOX:-}" =~ ^(1|true)$ ]]; then
    scripts/build_sandbox.sh -s
fi
